spring:
  application:
    name: TmT

  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useSSL=false&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 494d31e54fba839b5ff76e4797f5a7d8
#            client-secret: your-client-secret
#            redirect-uri: "https://localhost:8080/login/oauth2/code/kakao"
#            authorization-grant-type: authorization_code
#            scope: 
#            client-name: Kakao
#            provider: kakao
#
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id           

mybatis:
  mapper-locations: classpath*:mappers/*.xml  # 매핑 파일 위치 설정
  type-aliases-package: com.ssafy.TmT.dto

TnT:
  secret-key: "yourSuperSecureSecretKeyWith32CharactersOrMore!"
