spring:
  application:
    name: TmT

  datasource:
    url: jdbc:mysql://phoenixdb.cls4oq20gmca.ap-northeast-2.rds.amazonaws.com:3306/TeemoDB?serverTimezone=Asia/Seoul
    username: admin
    password: admin1013
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 494d31e54fba839b5ff76e4797f5a7d8
            client-secret: RU5B76ilxdp8TDJU3lGTjDoIu0OJ1erg
#            redirect-uri: "https://www.teemobudget.site/login/kakao/code"
            redirect-uri: "http://localhost:5173/login/kakao/code"
            authorization-grant-type: authorization_code
            scope: 
            client-name: Kakao
            provider: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id           

mybatis:
  mapper-locations: classpath*:mappers/*.xml  # 매핑 파일 위치 설정
  type-aliases-package: com.ssafy.TmT.dto
  configuration: 
    map-underscore-to-camel-case: true
    

TnT:
  secret-key: "yourSuperSecureSecretKeyWith32CharactersOrMore!"